### ISSUE TITLE
没有配置工作。 客户端连接，但没有加载任何内容。 好像没有网络

### ISSUE THREAD

**Issue by DevLothen** [wanliyunyan/xray_ios#1]
你好！. 我正在使用库做我的客户端，我面临着没有任何配置工作的问题。 什么都没有加载，就好像没有互联网。
我试图建立你的项目和完全相同的情况。 VPN已连接，但没有任何工作

你能告诉我看什么吗？ 客户是从俄罗斯推出的

我试图用XrayKit运行Mango项目，一切都在那里连接，但是如果将库更改为LibXray，则没有任何工作

**Comment by wanliyunyan** [comment]
You can communicate with me in English. https://github.com/EbrahimTahernejad/Tun2SocksKit/issues/21, I also saw this issue.I’m sure my project works. With a question like this, I’m not sure why your project isn’t working. I need more details

**Comment by sergeymartynovich02** [comment]
@wanliyunyan hi! Do you have telegram? I would like to ask you a couple of questions about the implementation because nothing works for me after connecting

**Comment by wanliyunyan** [comment]
@sergeymartynovich02 China and Russia have a time difference, so let’s communicate on GitHub instead.
