### ISSUE TITLE
为什么日志到：VPN 配置已保存并加载 VPN 启动成功。就停止不动了，也连接不上vpn

### ISSUE THREAD

**Issue by LBBB** [wanliyunyan/xray_ios#10]
为什么日志到：VPN 配置已保存并加载 VPN 启动成功。就停止不动了，也连接不上vpn

**Comment by wanliyunyan** [comment]
我试了一下，没问题啊，好使啊，我复现不了你的问题

**Comment by LBBB** [comment]
嗯嗯大哥，我的是vmess协议，需要改哪里吗？

**Comment by wanliyunyan** [comment]
我不敢用vmess协议，封的太厉害了，我还真不知道怎么改。。。

**Comment by LBBB** [comment]
。。好吧，这段代码不支持vmess吗？我是新手。。

**Comment by LBBB** [comment]
那您的封装的[LibXray](https://github.com/wanliyunyan/LibXray)是Xray-core的通用的吗？我可以用来实现vmess协议吗？

**Comment by wanliyunyan** [comment]
我觉得都应该支持，我也是新手，但是我没测过，我也不敢说，因为是Xray-core读取的配置，和其它代码应该是没关系的，这个库是打包的 https://github.com/XTLS/libXray

**Comment by LBBB** [comment]
哦哦，我也是看的这个仓库，那应该是通用的，方便加您的联系方式吗？我的wx是zgrmwanm

**Comment by wanliyunyan** [comment]
这个不太方便。。。，你也把你这条回复删了吧，微信id别被爬虫爬到了

**Comment by LBBB** [comment]
嗯嗯，知道了好吧

**Comment by LBBB** [comment]
能告诉我怎么打包https://github.com/XTLS/libXray吗，有博客吗谢谢

**Comment by wanliyunyan** [comment]
https://github.com/XTLS/libXray/blob/main/build/README.md

**Comment by LBBB** [comment]
嗯嗯谢谢大哥
