### ISSUE TITLE
设置里选中其他的vpn 在点击链接时会报错

### ISSUE THREAD

**Issue by AMNESIA-s** [wanliyunyan/xray_ios#5]
![111729172046_ pic](https://github.com/user-attachments/assets/220f39d1-6941-4bb6-90dd-77c9fa52ad8f)
<img width="495" alt="image" src="https://github.com/user-attachments/assets/1d185c00-0a6a-4889-9479-85212a01cf5c">

**Comment by wanliyunyan** [comment]
这肯定是启动哪个app，设置就是哪个app啊，别的肯定报错啊，代码必须和手机vpn中的配置一一对应的

**Comment by AMNESIA-s** [comment]
我的意思是已经连其他的VPN再连的话 会有问题 当然这不是bug 我只是想知道有没有什么方案能丝滑切换VPN

**Comment by wanliyunyan** [comment]
这个我也不知道🤭
