### ISSUE TITLE
你好，请问下这个demo的代码被上架过App Store应用商店吗？

### ISSUE THREAD

**Issue by jctrace** [wanliyunyan/xray_ios#6]

**Comment by wanliyunyan** [comment]
不清楚，现在vpn 应该跟难上 appstore

**Comment by popularteam** [comment]
@wanliyunyan 里面的库是你自己编译的吗？还是从别的仓库下载的？

**Comment by popularteam** [comment]
直接用来上架App Store，大概率4.3（重复代码），如果有能力直接混淆SDK源码，或者自己重写源码，概率会高一点。

**Comment by wanliyunyan** [comment]
@popularteam 我自己从 https://github.com/XTLS/libXray 编译的

**Comment by wanliyunyan** [comment]
@popularteam 引用这种第三方依赖，上 AppStore 会 4.3？AppStore这么弄不科学啊....

**Comment by popularteam** [comment]
@wanliyunyan 暂时还不用纠结这个，等遇到的时候再说吧。我有一个配置，放其他软件上能连，用这个项目连上没网，能给个邮箱吗？我把配置发给你，一起研究一下。

**Comment by wanliyunyan** [comment]
@popularteam xiaosheng@cloud-unicom.cn
