### ISSUE TITLE
第一次运行功能都正常，只要再用过其他家像小火箭这样的软件后，再运行这个demo，就会报错连接不上，不能自动切换到demo自己的配置，还是停留在其他的配置，需要手动切换到demo的Xray配置，才可以正常运行

### ISSUE THREAD

**Issue by jctrace** [wanliyunyan/xray_ios#8]
第一次运行，允许添加配置，点击连接，功能都是正常的。但是再用其他家像小火箭这样的软件后，再点击连接运行这个demo，就没反应，并且控制台报错：The operation couldn’t be completed. (NEVPNErrorDomain error 2.)，原因是点击连接按钮，如果已经添加了配置，不能自动切换到demo自己的Xray配置，还是停留在其他的像小火箭这样的软件配置文件，需要手动去勾选这个demo的Xray配置。
![demo](https://github.com/user-attachments/assets/e531d745-5128-42e5-96d5-e699a969abca)

**Comment by wanliyunyan** [comment]
这几天忙，得过两天看

**Comment by wanliyunyan** [comment]
@jctrace 改好了

**Comment by jctrace** [comment]
👍👍
