### ISSUE TITLE
参考了您的部分逻辑，想借此做一个MacOS端的～但是在隧道层发生一些难以理解的问题。

### ISSUE THREAD

**Issue by seekky** [wanliyunyan/xray_ios#9]
其实找到您这个项目之前，我就已经碰到了这个问题。
我本来的打算是利用Tun2Socks捕获tun接口，包装成socks后转发至旁路利用Process()直接开启Xray监听隧道的转发。
但是后来怎么也无法在NE将隧道建立后开启Tun2Socks=。=（连返回都没有，日志就是无限重连，隧道关闭的瞬间会返回code 0开启成功～）
后来又尝试了利用NE自身的http和https代理直接转发至Xray，让Xray监听http协议，结果packet可以一路跑到节点，但是Xray会大量报错，无限重连节点，应该是Packet的结构有问题，或者PacketTunnel拒绝建立连接？

仔细研究了你的代码后发现，你是在PacketTunnel的线程中运行的Tun2Socks和Xray，所以，苹果是不是对NE的使用有特别的要求？比如PacketTunnel会拒绝通往外部线程的回传流量？或者其他的权限原因？

所以，我必须在PacketTunnel线程中处理完所有的流量加密，直接与外部服务器建立连接？
反正不管是隧道内的Tun2Socks，或者NE本身，好像与本地的其他线程建立连接后，都会有各种各样的问题。
望解惑。。。

另外，NE扩展真的好烦人啊，全是坑，各种限制，踩完一个又一个，最近看到swift就头大，都是他害的=。=

**Comment by wanliyunyan** [comment]
我也是照别人例子模仿的做了一个ios的例子，等我有空研究一下macos，现在忙，没时间。。。。

**Comment by seekky** [comment]
哈～我搞定了，果然还是NE的限制，外部的进程如果接管数据流会出现异常。
所以只能使用libxray让流量处理完全在PacketTunnel中完成。
不然直接外部开启xray的话，岂不是可以很轻松的绕过NE对VPN的内存限制？=。=

另外因为这两天因为我详细的研究了一下您的代码，所以，发现其实有些地方还是可以优化的。
比如，您可以调用NEProxySettings，直接让NE转发http和https代理到xray，xray那边同时建2个监听，一个监听http，一个监听socks。NE还是会自动分流http和https的流量。

因为直接利用http的话，相关流量会减少一道socks的加解密过程。而且类似chatGPT客户端这种基于http交互的应用，也不会发生断连的情况。（我也是详细研究了shadowrocket的转发机制才发现的）

没什么特别的问题的话，这个issue可以关啦～有机会的话，希望能与你交个朋友

**Comment by wanliyunyan** [comment]
还是大佬厉害，懂的多，我才研究swift和vpn技术两个月，我以前没搞过这东西，我也是看没有人用swfit写ios端，我合计我就照别人模仿一个例子吧，像你说的自动分流加密，我以前完全都没有考虑过，我有空学习学习，我也希望和你交个朋友

**Comment by seekky** [comment]
我也称不上大佬啦～我tg也是seekky，有空可以交流交流。swift写的案例确实少，之前都是oc的。而且这几本也都是国人在搞，国外人家没这个需求～确实能参考的东西不多。最近有个客户要做这个，想着做了就一步到位，前几年都是直接搞个核心监听个socks，然后也是用Process方法修改系统的networksetup，打开系统的socks代理这种半吊子方法。
结果好了=。=NE全是坑，不开沙盒找不到Bundle id，也不报个错，进程外回传流量不收也不说一下，害得我一直以为是核心那边设置有问题。
总之，有空可以聊聊，互相学习一下经验吧，大家踩过的坑不要重复踩了
